
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-happycows-f25-14
owner: ucsb-cs156-f25
repo_name: proj-happycows-f25-14
pull_requests: [{"author":{"id":"U_kgDOCOTuMA","is_bot":false,"login":"cthrnzhong","name":""},"headRefName":"cthrnzhong-crud-op-for-admin","number":28,"title":"cthrnzhong - added CRUD operations for admin","url":"https://github.com/ucsb-cs156-f25/proj-happycows-f25-14/pull/28"},{"author":{"id":"U_kgDOCujG6A","is_bot":false,"login":"danielc-285","name":""},"headRefName":"dc-ux-refactor","number":19,"title":"dc - UX Refactor by adding pagination for chat messages. ","url":"https://github.com/ucsb-cs156-f25/proj-happycows-f25-14/pull/19"},{"author":{"id":"U_kgDOCvCqLg","is_bot":false,"login":"PratimaNallapareddy","name":"Pratima R Nallapareddy"},"headRefName":"pn-addLauncherForRecordCommonStats","number":18,"title":"Pn add launcher for record common stats","url":"https://github.com/ucsb-cs156-f25/proj-happycows-f25-14/pull/18"},{"author":{"id":"U_kgDOCvCqLg","is_bot":false,"login":"PratimaNallapareddy","name":"Pratima R Nallapareddy"},"headRefName":"pn-RecordCommonStatsForm-placeholder","number":17,"title":"pn-created placeholder RecordCommonStatsForm and test files","url":"https://github.com/ucsb-cs156-f25/proj-happycows-f25-14/pull/17"},{"author":{"id":"U_kgDOCVHRvw","is_bot":false,"login":"logan-melgoza","name":"Logan Melgoza"},"headRefName":"lm-eslint-rules","number":15,"title":"lm - [TASK] Reintroduce React ESLint Rules (#7)","url":"https://github.com/ucsb-cs156-f25/proj-happycows-f25-14/pull/15"},{"author":{"id":"U_kgDOCM73Qg","is_bot":false,"login":"KeyiZong27","name":"KEYI ZONG"},"headRefName":"kz-admin-list-common-page","number":11,"title":"Change List Commons Page","url":"https://github.com/ucsb-cs156-f25/proj-happycows-f25-14/pull/11"}]
