
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-happycows-f25-14
owner: ucsb-cs156-f25
repo_name: proj-happycows-f25-14
pull_requests: [{"author":{"id":"U_kgDOCIZ8Xg","is_bot":false,"login":"Fern4ndo99","name":""},"headRefName":"FV-wiremock/upgrade","number":12,"title":"Fv - wiremock/upgrade","url":"https://github.com/ucsb-cs156-f25/proj-happycows-f25-14/pull/12"},{"author":{"id":"U_kgDOCM73Qg","is_bot":false,"login":"KeyiZong27","name":"KEYI ZONG"},"headRefName":"kz-admin-list-common-page","number":11,"title":"Change List Commons Page","url":"https://github.com/ucsb-cs156-f25/proj-happycows-f25-14/pull/11"},{"author":{"id":"U_kgDOCIZ8Xg","is_bot":false,"login":"Fern4ndo99","name":""},"headRefName":"FV-Admin/DeveloperInfoPage","number":8,"title":"fv - Add Developer Info page with repo link and system info","url":"https://github.com/ucsb-cs156-f25/proj-happycows-f25-14/pull/8"}]
