
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-happycows-f25-14
owner: ucsb-cs156-f25
repo_name: proj-happycows-f25-14
pull_requests: [{"author":{"id":"U_kgDOCOTuMA","is_bot":false,"login":"cthrnzhong","name":""},"headRefName":"cthrnzhong-restore-title-and-favicon","number":9,"title":"changed title to Happycows and added correct favicon","url":"https://github.com/ucsb-cs156-f25/proj-happycows-f25-14/pull/9"},{"author":{"id":"U_kgDOCIZ8Xg","is_bot":false,"login":"Fern4ndo99","name":""},"headRefName":"FV-Admin/DeveloperInfoPage","number":8,"title":"fv - Add Developer Info page with repo link and system info","url":"https://github.com/ucsb-cs156-f25/proj-happycows-f25-14/pull/8"}]
